### ISSUE TITLE
 CdrEvent:  Null Values for Non-Nullable Source/Destination

### ISSUE THREAD

**Issue by jamabaiz** [sufficit/sufficit-asterisk-core#3]
Hello

I found out that `CdrEvent` class has `nullable enabled` with `Destination` and `Src` not nullabe. 

But sometimes i receive events with null values like on screen below:
![image](https://github.com/user-attachments/assets/47658bb2-656a-45c8-9046-e8f908fdc584)

Its required to force fallback null value on `non-nullable` property.

**Comment by hugodeco** [comment]
Many still remain that way, because we don't use those and we don't know exactly what can be null and what can't.

**Comment by jamabaiz** [comment]
I understand. In that case, it would probably be safer to mark all those you don't know as nullable. Because this causes unexpected errors later. It's strange to do things like that:

![image](https://github.com/user-attachments/assets/6b56787e-e5fa-4049-bbd8-e3111d1cf9ad)

Enured non-nullable, might by marked with `required` modifier.

**Comment by jamabaiz** [comment]
I checked out that you applied changes in b4bddc938e15285f5d6bcb6e85dd5e44e4bd37e5. That's fine.
Thanks!
